### ISSUE TITLE
resources failing to load if host page served under https

### ISSUE THREAD

**Issue by carueda** [OpenTriply/YASGUI#80]
I've been including the base scripts as suggested:

```html
<link href='//cdn.jsdelivr.net/yasgui/2.2.1/yasgui.min.css' rel='stylesheet' type='text/css'/>
<script src='//cdn.jsdelivr.net/yasgui/2.2.1/yasgui.min.js'></script>
```

In particular, with the usual `href=//...` mechanism to make the page work well whether it's served under HTTP or HTTPS.

Now that I'm switching to HTTPS I note that it is not actually working as expected because there still are some underlying resources being requested in an insecure way:

- http://prefix.cc/popular/all.file.json
- http://google.com/jsapi

Those resources are actually available via HTTPS as well.

![image](https://cloud.githubusercontent.com/assets/556505/14753457/649e8c6e-088a-11e6-9b6a-22a37b825140.png)

**Comment by LaurensRietveld** [comment]
Indeed we should support ssl asap. A list of todo's:

- [ ] https://github.com/OpenTriply/YASGUI.YASR/issues/84 : Disable preflabel requests when YASR is hosted via https
- [ ] https://github.com/OpenTriply/YASGUI.YASQE/issues/79: Support https requests to prefix.cc
- [ ] https://github.com/OpenTriply/YASGUI.YASQE/issues/80: Disable LOV autocompletions when YASQE is hosted via https
- [x] Use protocol relative request to google jsapi (https://github.com/OpenTriply/YASGUI.YASR/pull/82). Already fixed, but not properly propagated yet to current YASGUI version (will do this together with other https related issues)

**Comment by LaurensRietveld** [comment]
Could you check whether the last version (2.3.0) of YASGUI fits the bill and works properly?

**Comment by LaurensRietveld** [comment]
correction: try the 2.3.1 version. It contains a bugfix for YASR

**Comment by carueda** [comment]
The resources I mentioned are now loading fine with 2.3.1, thanks.

Since my YASGUI page is located on the same SPARQL server I adjusted my config to have:

```js
YASGUI.YASQE.defaults.sparql.endpoint = "/sparql"
```

expecting that it would also be handled well for both secure and insecure access, but I get:

```
Mixed Content: The page at 'https://myserver/my-yagui-page' was loaded over HTTPS, 
but requested an insecure XMLHttpRequest endpoint 'http://myserver/sparql'. 
This request has been blocked; the content must be served over HTTPS.
```

Should I set `YASGUI.YASQE.defaults.sparql.endpoint` as appropriate on my side, or could YASGUI.YASQE take care of that?

Thanks again!

**Comment by LaurensRietveld** [comment]
Ah, this is probably a caching issue, that can be resolved by clearing the local storage of your browser for that particular domain. To test whether this is indeed an issue, try your site with a different browser, or in 'private mode'. 

This is related to the issue of passing YASQE and YASR configurations to YASGUI. Right now, using the defaults value is the only option, but these get overwritten to already existing settings (in this case: local storage). I'll have to take a better look on how to pass these options to YASGUI, without using the 'defaults' hacky method.

ps. You could consider hiding the endpoint selection completely via css (`.endpointText {display:none}`), instead of only emptying the pre-filled list of available endpoints.

**Comment by carueda** [comment]
Yes, it was a catching issue.  But before I cleared it, just as a quick test, I explicitly set the endpoint to use my HTTPS one, and all works well with it.

And yes, in my case I can certainly hide the endpoint selection, thanks for the suggestion.

Thanks again for the fix!

**Comment by carueda** [comment]
Just closing, thanks again.
